config/routes.rb
MyRubyChina::Application.routes.draw do
  resources :topics, only: [:index, :show, :new, :create] do
    resources :replies, only: [:create]
  end
  
  resources :nodes, only: [:show]
  resources :users, only: [:show, :create]
  resources :sessions, only: [:create]

  root to: "topics#index"

  match 'sign_up', to: "users#new"
  match 'sign_in', to: "sessions#new"
  match 'ui/:action', controller: 'ui'

end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :name, :description

  has_many :topics
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :content, :topic, :user

  belongs_to :topic
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :title, :node, :content, :node_id, :author

  belongs_to :node
  belongs_to :author, class_name: "User"
  
  has_many :replies
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email

  has_many :topics, :class_name => "Topic", :foreign_key => "author_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private
  def current_user
    user = User.new
    user = User.find_by_name(session[:user_name]) if session[:user_name]
    user
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  def show
    @node = Node.find(params[:id])
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    topic = Topic.find(params[:topic_id])
    reply = topic.replies.build params[:reply]
    reply.user = current_user
    reply.save

    redirect_to topic
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    session[:user_name] = params[:user_name]
    redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    topic = Topic.new params[:topic]
    topic.author = current_user
    topic.save

    redirect_to root_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_filter do
    redirect_to :root if Rails.env.production?
  end

  layout "application"

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    User.create(params[:user])

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(email)
    hash = Digest::MD5.hexdigest(email.downcase)
    "//www.gravatar.com/avatar/#{hash}?s=47"
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title A clone of ruby-china.org
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = yield :head
  %body
    %header
      %section.container
        %h3
          %a(href="/")
            %img(src="/assets/text_logo.png")
        %ul.span3
          %li
            = link_to "社区"
          %li
            = link_to "会员"
        .dropdown
          %a(class="dropdown-toggle" id="dlabel" role="button" data-toggle="dropdown" data-target="#" href="#")
            = current_user.name
            %b.caret
          %ul(class= "dropdown-menu" role="menu" aria-labelledby='dLabel')
            %li
              = link_to "退出"
    %section.container
      = yield
    %footer

app/views/nodes/show.html.haml
= render 'shared/breadcrumb', links: [["Home", ""], ["社区", ""], ["Ruby", ""]]

%section#node_topics
  %section#node_info.box.box-gray.info-box
    %h2= @node.name
    %span 共有48个讨论主题
    %p= @node.description
  = render 'topics/topics', topics: @node.topics

%section#sidebar
  %section#new_topic.box
    = link_to "发布新帖", nil, class: "btn btn-success"
  %section#stats.box
    %ul
      %li 社区会员: 4029 人
      %li 帖子数: 312 篇
      %li 回帖数: 3123 条

app/views/shared/_breadcrumb.html.haml
%ul.breadcrumb
  - links.each do |link|
    %li
      = link_to link.first, link.last
      - unless link == links.last
        %span.divider /

app/views/topics/_topics.html.haml
%ul.topics.box
  - topics.each do |topic|
    %li
      %a.span1(href="")
        %img(src="#{gravatar_url('joe@example.com')}")
      %article.span7
        %p.topic_title
          = link_to topic.title
        %p.topic_info
          = link_to topic.node.name, topic.node, class: "node"
          %span= "  •  "
          = link_to topic.author.name, topic.author, class: "user_link"
          %span= "  •  "
          = "published #{time_ago_in_words(topic.created_at)} ago"
          - last_replay = topic.replies.last
          - if last_replay
            %span= "  •  "
            last replied by
            = link_to last_replay.user.name, last_replay.user, class: "user_link"
            = "#{time_ago_in_words(last_replay.created_at)} ago"

      %p.replies.span1
        %span 12

app/views/topics/index.html.haml
= render 'shared/breadcrumb', links: [["Home", ""], ["社区", ""]]

%section#topics
  %section#topics_info.box.box-gray.info-box
    %span 查看： 默认
  = render 'topics', topics: @topics

%section#sidebar
  %section#new_topic.box
    = link_to "发布新帖", new_topic_path, class: "btn btn-success"
  %section#stats.box
    %ul
      %li 社区会员: 4029 人
      %li 帖子数: 312 篇
      %li 回帖数: 3123 条

app/views/topics/new.html.haml
= render 'shared/breadcrumb', links: [["Home", ""], ["社区", ""], ["发帖", ""]]

%section#new_topic.box
  %h1 新建帖子
  = form_for @topic, html: {class: "form-horizontal"} do |f|
    .control-group
      = f.label "标题", class: "control-label"
      .controls
        = f.select :node_id, Node.all.map{ |node| [node.name, node.id] }
        = f.text_field :title
    .control-group
      = f.label "正文"
      .controls
        = f.text_area :content, rows: 20
    .submit-button
      = f.submit "保存", class: "btn btn-primary"
      = link_to "取消"

%section#sidebar
  %section#new_post_note.box
    %h2 发帖说明
    %p 没啥可说的，发就是了

app/views/topics/show.html.haml
= render 'shared/breadcrumb', links: [["Home", root_path], [@topic.node.name, @topic.node], ["浏览帖子", @topic]]

%section#show_topic
  %section#topic_banner.box.info-box
    %h1= @topic.title
    %p.topic_info
      = link_to @topic.node.name, @topic.node, class: "node"
      %span= "  •  "
      = link_to "knwang", nil, class: "user_link"
      %span= "  •  "
      = "published #{@topic.created_at} ago"
  %section#topic_content.box
    %p= @topic.content

  %section#replies_banner.box.info-box
    %span= "共收到 #{@topic.replies.count} 条回复"

  %section#replies.box
    %ul
      - @topic.replies.each do |reply|
        %li
          %a.span1(href="")
            %img(src="#{gravatar_url('joe@example.com')}")
          %article.span8
            = link_to "knwang", nil, class: "user_link"
            %span= "#{time_ago_in_words(reply.created_at)} ago"
            %p= reply.content

  %section#reply.box
    = form_for [@topic, Reply.new] do |f|
      = f.text_area :content, rows: 4
      = f.submit "提交回复", class: "btn btn-primary"


%section#sidebar
  %section#new_topic.box
    = link_to "发布新帖", nil, class: "btn btn-success"
  %section#stats.box
    %ul
      %li 社区会员: 4029 人
      %li 帖子数: 312 篇
      %li 回帖数: 3123 条

app/views/ui/index.html.haml
.box.box-gray
  %ul
    - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
      - wireframe = File.basename(file, '.html.haml')
      - unless wireframe == 'index' || wireframe.match(/^_/)
        %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'

app/views/ui/new_topic.html.haml
= render 'shared/breadcrumb', links: [["Home", ""], ["社区", ""], ["发帖", ""]]

%section#new_topic.box
  %h1 新建帖子
  %form(action="" method="post" class="form-horizontal")
    .control-group
      %label(class="control-label") 标题
      .controls
        %select
          %option(value="Ruby") Ruby
          %option(value="Rails") Rails
          %option(value="XiaCheDan") XiaCheDan
        %input(type="text")
    .control-group
      %label(class="control-label") 正文
      .controls
        %textarea(rows="20")
    .submit-button
      %input(type="submit" value="保存" class="btn btn-primary")
      = link_to "取消"

%section#sidebar
  %section#new_post_note.box
    %h2 发帖说明
    %p 没啥可说的，发就是了

app/views/ui/node.html.haml
= render 'shared/breadcrumb', links: [["Home", ""], ["社区", ""], ["Ruby", ""]]

%section#node_topics
  %section#node_info.box.box-gray.info-box
    %h2 Ruby
    %span 共有48个讨论主题
    %p Ruby是一门优美的语言
  %ul.topics.box
    %li
      %a.span1(href="")
        %img(src="#{gravatar_url('joe@example.com')}")
      %article.span7
        %p.topic_title
          = link_to "DHH 的公开课"
        %p.topic_info
          = link_to "分享", nil, class: "node"
          %span= "  •  "
          = link_to "knwang", nil, class: "user_link"
          %span= "  •  "
          published 3 mintes ago
      %p.replies.span1
        %span 12
    %li
      %a.span1(href="")
        %img(src="#{gravatar_url('joe@example.com')}")
      %article.span7
        %p.topic_title
          = link_to "Rails3 中 compass 的 IE 使用问题"
        %p.topic_info
          = link_to "分享", nil, class: "node"
          %span= "  •  "
          = link_to "knwang", nil, class: "user_link"
          %span= "  •  "
          last replied by
          = link_to "knwang", nil, class: "user_link"
          4 mintes ago
      %p.replies.span1
        %span 12
    %li
      %a.span1(href="")
        %img(src="#{gravatar_url('joe@example.com')}")
      %article.span7
        %p.topic_title
          = link_to "这周二上海搞Ruby Tuesday么？"
        %p.topic_info
          = link_to "分享", nil, class: "node"
          %span= "  •  "
          = link_to "knwang", nil, class: "user_link"
          %span= "  •  "
          last replied by
          = link_to "knwang", nil, class: "user_link"
          8 mintes ago
      %p.replies.span1
        %span 12

%section#sidebar
  %section#new_topic.box
    = link_to "发布新帖", nil, class: "btn btn-success"
  %section#stats.box
    %ul
      %li 社区会员: 4029 人
      %li 帖子数: 312 篇
      %li 回帖数: 3123 条

app/views/ui/signin.html.haml
= render 'shared/breadcrumb', links: [["Home", ""]]

%section#sign_in.box
  %h1 登录
  %form(action="" method="post" class="form-horizontal")
    .control-group
      %label(class="control-label") 用户名
      .controls
        %input(type="text")
    .submit-button
      %input(type="submit" value="登录" class="btn btn-primary")

%section#sidebar
  %section#has_account.box
    %h2 还没有帐号?
    = link_to "注册"

app/views/ui/signup.html.haml
= render 'shared/breadcrumb', links: [["Home", ""]]

%section#new_user.box
  %h1 注册新用户
  %form(action="" method="post" class="form-horizontal")
    .control-group
      %label(class="control-label") 用户名
      .controls
        %input(type="text")
      %label(class="control-label") Email
      .controls
        %input(type="text" placeholder="foo@bar.com")
    .submit-button
      %input(type="submit" value="提交注册信息" class="btn btn-primary")

%section#sidebar
  %section#has_account.box
    %h2 已经有帐号了？
    = link_to "登录"

app/views/ui/topic.html.haml
= render 'shared/breadcrumb', links: [["Home", ""], ["社区", ""], ["新手问题", ""], ["浏览帖子", ""]]

%section#show_topic
  %section#topic_banner.box.info-box
    %h1 有没有熟悉人工智能的同学
    %p.topic_info
      = link_to "分享", nil, class: "node"
      %span= "  •  "
      = link_to "knwang", nil, class: "user_link"
      %span= "  •  "
      published 3 mintes ago
  %section#topic_content.box
    %p
      这学期选了门AI的课。
      %br
      %br

      本科生可以写一份8页的报告来赚点额外的分，因为对这个领域实在不太了解所以想求大神们给点方向和题目。
      %br
      %br

      报告不长，大概的结构是这样的：
      * 开头
      **** 所用的领域和要解决的问题
      * 解决方法
      **** 找一下现有的解决方案
      **** 比较一下这些解决方案（优缺点，scability，是否易用）
      * 总结

  %section#replies_banner.box.info-box
    %span 共收到 5 条回复

  %section#replies.box
    %ul
      %li
        %a.span1(href="")
          %img(src="#{gravatar_url('joe@example.com')}")
        %article.span8
          = link_to "knwang", nil, class: "user_link"
          %span two hours ago
          %p ++ -- 这个操作就是罪恶的源泉。。++ -- 这个操作就是罪恶的源泉。。++ -- 这个操作就是罪恶的源泉。。++ -- 这个操作就是罪恶的源泉。。++ -- 这个操作就是罪恶的源泉。。++ -- 这个操作就是罪恶的源泉。。
      %li
        %a.span1(href="")
          %img(src="#{gravatar_url('joe@example.com')}")
        %article.span8
          = link_to "knwang", nil, class: "user_link"
          %span two hours ago
          %p ++ -- 这个操作就是罪恶的源泉。。
      %li
        %a.span1(href="")
          %img(src="#{gravatar_url('joe@example.com')}")
        %article.span8
          = link_to "knwang", nil, class: "user_link"
          %span two hours ago
          %p ++ -- 这个操作就是罪恶的源泉。。

  %section#reply.box
    %form(action="" method="post")
      %textarea(rows="4")
      %input(type="submit" class="btn btn-primary" value="提交回复")

%section#sidebar
  %section#new_topic.box
    = link_to "发布新帖", nil, class: "btn btn-success"
  %section#stats.box
    %ul
      %li 社区会员: 4029 人
      %li 帖子数: 312 篇
      %li 回帖数: 3123 条

app/views/ui/topics.html.haml
= render 'shared/breadcrumb', links: [["Home", ""], ["社区", ""]]

%section#topics
  %section#topics_info.box.box-gray.info-box
    %span 查看： 默认
  %ul.topics.box
    %li
      %a.span1(href="")
        %img(src="#{gravatar_url('joe@example.com')}")
      %article.span7
        %p.topic_title
          = link_to "DHH 的公开课"
        %p.topic_info
          = link_to "分享", nil, class: "node"
          %span= "  •  "
          = link_to "knwang", nil, class: "user_link"
          %span= "  •  "
          published 3 mintes ago
      %p.replies.span1
        %span 12
    %li
      %a.span1(href="")
        %img(src="#{gravatar_url('joe@example.com')}")
      %article.span7
        %p.topic_title
          = link_to "Rails3 中 compass 的 IE 使用问题"
        %p.topic_info
          = link_to "分享", nil, class: "node"
          %span= "  •  "
          = link_to "knwang", nil, class: "user_link"
          %span= "  •  "
          last replied by
          = link_to "knwang", nil, class: "user_link"
          4 mintes ago
      %p.replies.span1
        %span 12
    %li
      %a.span1(href="")
        %img(src="#{gravatar_url('joe@example.com')}")
      %article.span7
        %p.topic_title
          = link_to "这周二上海搞Ruby Tuesday么？"
        %p.topic_info
          = link_to "分享", nil, class: "node"
          %span= "  •  "
          = link_to "knwang", nil, class: "user_link"
          %span= "  •  "
          last replied by
          = link_to "knwang", nil, class: "user_link"
          8 mintes ago
      %p.replies.span1
        %span 12

%section#sidebar
  %section#new_topic.box
    = link_to "发布新帖", nil, class: "btn btn-success"
  %section#stats.box
    %ul
      %li 社区会员: 4029 人
      %li 帖子数: 312 篇
      %li 回帖数: 3123 条

app/views/ui/user.html.haml
%section#user.box
  %h1 个人信息
  %img(src="#{gravatar_url('joe@example.com')}")
  %dl
    %dt.span1 ID:
    %dd
      %strong chucai
    %dt.span1 Since:
    %dd 2012年2月12日

%section#user_recent_topics.box
  %section#user_recent_topics_banner.box.info-box
    %span 最近发布的帖子
  %section#user_recent_topics_content.box
    %ul
      %li
        = link_to "Rails", nil, class: "node"
        = link_to "BDD开发模式:使用Rspec开发Rails Project的标准流程是什么?"
        %span 3 days ago
      %li
        = link_to "Rails", nil, class: "node"
        = link_to "BDD开发模式:使用Rspec开发Rails Project的标准流程是什么?"
        %span 3 days ago
      %li
        = link_to "Rails", nil, class: "node"
        = link_to "BDD开发模式:使用Rspec开发Rails Project的标准流程是什么?"
        %span 3 days ago

%section#user_recent_replies.box
  %section#user_recent_replies_banner.box.info-box
    %span 最近回复的帖子
  %section#user_recent_replies_content.box
    %ul
      %li
        = link_to "[北京][2012年10月9日] 周二晚上8点小聚，有烤羊腿等着你"
        %span 3 days ago
        %p 21号有
      %li
        = link_to "[北京][2012年10月9日] 周二晚上8点小聚，有烤羊腿等着你"
        %span 3 days ago
        %p 21号有
      %li
        = link_to "[北京][2012年10月9日] 周二晚上8点小聚，有烤羊腿等着你"
        %span 3 days ago
        %p 21号有

app/views/users/new.html.haml
= render 'shared/breadcrumb', links: [["Home", ""]]

%section#new_user.box
  %h1 注册新用户
  = form_for @user, html: {class: "form-horizontal"} do |f|
    .control-group
      = f.label "用户名", class: "control-label"
      .controls
        = f.text_field :name
    .control-group
      = f.label "Email", class: "control-label"
      .controls
        = f.text_field :email, placeholder: "foo@bar.com"
    .submit-button
      = f.submit "提交注册信息", class: "btn btn-primary"

%section#sidebar
  %section#has_account.box
    %h2 已经有帐号了？
    = link_to "登录"

app/views/users/show.html.haml
%section#user.box
  %h1 个人信息
  %img(src="#{gravatar_url('joe@example.com')}")
  %dl
    %dt.span1 ID:
    %dd
      %strong= @user.name
    %dt.span1 Since:
    %dd= @user.created_at

%section#user_recent_topics.box
  %section#user_recent_topics_banner.box.info-box
    %span 最近发布的帖子
  %section#user_recent_topics_content.box
    %ul
      - @user.topics.each do |topic|
        %li
          = link_to topic.node.name, topic.node, class: "node"
          = link_to topic.title, topic
          %span= "#{time_ago_in_words(topic.created_at)} ago"